CREATE TABLE votersdb_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL,
    full_name TEXT NOT NULL,
    password TEXT NOT NULL,
    addresses TEXT[],
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_modified TIMESTAMP
);